language: generic

sudo: false

env:
  - PYTHON_VERSION=2.7 CONDA_VERSION=4.2.16
  - PYTHON_VERSION=3.5 CONDA_VERSION=4.2.16
  - PYTHON_VERSION=3.6 CONDA_VERSION=4.2.16
  - PYTHON_VERSION=2.7 CONDA_VERSION=4.3.21
  - PYTHON_VERSION=3.5 CONDA_VERSION=4.3.21
  - PYTHON_VERSION=3.6 CONDA_VERSION=4.3.21
  - PYTHON_VERSION=2.7 CONDA_VERSION=4.5.3
  - PYTHON_VERSION=3.5 CONDA_VERSION=4.5.3
  - PYTHON_VERSION=3.6 CONDA_VERSION=4.5.3

install:
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  - conda config --set show_channel_urls True
  - conda install --yes python=$PYTHON_VERSION --file requirements.txt
  - conda config --set auto_update_conda False
  - conda install --yes conda=$CONDA_VERSION

  - python setup.py version
  - python setup.py install

script:
  - which python
  - which conda
  - conda info
  - conda execute --help
  - ./tests/run_tests.sh
