language: python

sudo: false

env:
  - python=2.7
  - python=3.4
  - python=3.5

install:
- export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
- wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
# - wget ${CONDA_BASE}-4.2.12-Linux-x86_64.sh -O miniconda.sh;
# to switch to an older version of conda, also need to remove conda from the requirements.txt file
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set show_channel_urls True
- conda config --set auto_update_conda False

- conda install --yes python=${python} --file requirements.txt

- python setup.py version
- python setup.py install

script:
- conda execute --help
- python -c "import conda_execute; print(conda_execute.__version__)"
- python -c "import conda; print(conda.__version__)"
- python -m conda info
- ./tests/run_tests.sh
